### ISSUE TITLE
[BUG] Deleted image does not get removed from filesystem

### ISSUE THREAD

**Issue by triszt4n** [kir-dev/warp-next#99]
If I delete a whole album, the images do not get removed from filesystem, so the newly registered short urls point to an old image, if I recreate the exact same album with e.g. smaller resolution.

**Comment by triszt4n** [comment]
Not only if album gets deleted, on each separate image deletion too :(

**Comment by Tschonti** [comment]
any updates on this??? xd

**Comment by triszt4n** [comment]
nope and not gonna have time. maybe Roli or someone with rails exp?
